"""Initial migration

Revision ID: d9439dc18973
Revises: 
Create Date: 2025-09-07 06:15:04.115326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9439dc18973'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove drop index and drop table for interactions to avoid error
    # op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    # op.drop_table('interactions')
    op.add_column('clients', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_unique_constraint(None, 'clients', ['email'])
    op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'])
    op.drop_column('clients', 'company')
    op.add_column('opportunities', sa.Column('name', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'users', ['assigned_user_id'], ['id'])
    op.drop_column('opportunities', 'estimated_value')
    op.drop_column('opportunities', 'title')
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('related_client_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('related_opportunity_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'opportunities', ['related_opportunity_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tasks', 'clients', ['related_client_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'])
    op.drop_column('tasks', 'completed')
    op.drop_column('tasks', 'assigned_to')
    op.drop_column('tasks', 'client_id')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'name')
    op.add_column('tasks', sa.Column('client_id', sa.INTEGER(), nullable=True))
    op.add_column('tasks', sa.Column('assigned_to', sa.INTEGER(), nullable=True))
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'tasks', 'clients', ['client_id'], ['id'])
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'related_opportunity_id')
    op.drop_column('tasks', 'related_client_id')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'assigned_user_id')
    op.drop_column('tasks', 'status')
    op.add_column('opportunities', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('opportunities', sa.Column('estimated_value', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'assigned_user_id')
    op.drop_column('opportunities', 'value')
    op.drop_column('opportunities', 'name')
    op.add_column('clients', sa.Column('company', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=1)
    op.drop_column('clients', 'created_by')
    op.drop_column('clients', 'company_id')
    op.create_table('interactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    # ### end Alembic commands ###
