version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  ai:
    build: ./microservices/ai
    ports:
      - "5000:5000"
